import Head from 'next/head';
import Link from 'next/link';
import { Tab } from '@headlessui/react';
import Masonry from 'react-masonry-css';
import classNames from 'classnames';
import Image from 'next/image';

import 'lightgallery/css/lightgallery.css';
import 'lightgallery/css/lg-zoom.css';
import 'lightgallery/css/lg-thumbnail.css';

import lgThumbnail from 'lightgallery/plugins/thumbnail';
import lgZoom from 'lightgallery/plugins/zoom';

import bgImage from '../public/images/photography-bg.jpg';

import { useRef } from 'react';
import LightGalleryComponent from 'lightgallery/react';
import type { LightGallery } from 'lightgallery/lightgallery';
import { GetStaticProps } from 'next';
import { createApi } from 'unsplash-js';
import * as nodeFetch from 'node-fetch';

const tabs = [
  {
    name: 'All',
  },
  {
    name: 'Ocean',
  },
  {
    name: 'Forest',
  },
];

const images = [
  {
    src: '/images/ocean-1.jpeg',
    thumb: '/images/ocean-1.jpeg',
  },
  {
    src: '/images/ocean-2.jpeg',
    thumb: '/images/ocean-1.jpeg',
  },
  {
    src: '/images/ocean-3.jpeg',
    thumb: '/images/ocean-3.jpeg',
  },
  {
    src: '/images/ocean-4.jpeg',
    thumb: '/images/ocean-4.jpeg',
  },
  {
    src: '/images/ocean-5.jpeg',
    thumb: '/images/ocean-5.jpeg',
  },
];

type Photo = {
  src: string;
  thumb: string;
  width: number;
  height: number;
  alt: string;
};

type HomeProps = {
  oceans: Photo[];
  forests: Photo[];
};

export const getStaticProps: GetStaticProps<HomeProps> = async () => {
  const unsplash = createApi({
    accessKey: process.env.UNSPLASH_ACCESS_KEY!,
    fetch: nodeFetch.default as unknown as typeof fetch,
  });

  const oceans = await unsplash.search.getPhotos({
    query: 'oceans',
  });

  const mappedOceans: Photo[] = [];

  if (oceans.type === 'success') {
    const oceanArr = oceans.response.results.map((photo, index) => ({
      src: photo.urls.full,
      thumb: photo.urls.thumb,
      width: photo.width,
      height: photo.height,
      alt: photo.alt_description ?? 'ocean-image' + index,
    }));

    mappedOceans.push(...oceanArr);
  } else {
    console.error("Couldn't find any photos");
  }

  const forests = await unsplash.search.getPhotos({
    query: 'forests',
  });

  const mappedForest: Photo[] = [];

  if (forests.type === 'success') {
    const forestArr = forests.response.results.map((photo, index) => ({
      src: photo.urls.full,
      thumb: photo.urls.thumb,
      width: photo.width,
      height: photo.height,
      alt: photo.alt_description ?? 'forest-image' + index,
    }));

    mappedForest.push(...forestArr);
  } else {
    console.error("Couldn't find any photos");
  }

  return {
    props: {
      oceans: mappedOceans,
      forests: mappedForest,
    },
  };
};

export default function Home({ oceans, forests }: HomeProps) {
  return (
    <div className="h-full overflow-auto">
      <Head>
        <title>Photography Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <Image
        className="fixed left-0 top-0"
        src={bgImage}
        alt=""
        placeholder="blur"
      />

      <div className="fixed left-0 top-0 w-full h-full from-stone-900 bg-gradient-to-t"></div>

      <header className="fixed top-0 w-full z-30 flex justify-between items-center h-[90px] px-6">
        <div className="hidden">hm</div>
        <span className="uppercase font-medium text-lg">
          Photography Portfolio
        </span>
        <Link
          href="#"
          className="rounded-3xl bg-white text-stone-600 px-5 py-3 hover:bg-opacity-90"
        >
          Get in touch
        </Link>
      </header>

      <main className="relative pt-[110px] z-20">
        <div className="flex flex-col items-center h-full">
          <Tab.Group>
            <Tab.List className="flex items-center gap-4">
              {tabs.map((tab, index) => (
                <Tab key={`${tab}-${index}`} className="p-2 uppercase">
                  {({ selected }) => (
                    <span
                      className={classNames(
                        'uppercase text-l',
                        selected ? 'text-white' : 'text-stone-600',
                      )}
                    >
                      {tab.name}
                    </span>
                  )}
                </Tab>
              ))}
            </Tab.List>
            <Tab.Panels className="h-full max-w-[900px] w-full p-2 sm:p-4 my-6">
              <Tab.Panel>
                <Gallery photos={[...oceans, ...forests]} />
              </Tab.Panel>
              <Tab.Panel>
                <Gallery photos={oceans} />
              </Tab.Panel>
              <Tab.Panel>
                <Gallery photos={forests} />
              </Tab.Panel>
            </Tab.Panels>
          </Tab.Group>
        </div>
      </main>

      <footer className="relative h-[90px] flex justify-center items-center uppercase text-lg font-medium z-20">
        <p>Photography Portfolio</p>
      </footer>
    </div>
  );
}

type GalleryProps = {
  photos: Photo[];
};

function Gallery({ photos }: GalleryProps) {
  const lightboxRef = useRef<LightGallery | null>(null);

  return (
    <>
      <Masonry breakpointCols={3} className="flex gap-4" columnClassName="">
        {photos.map((photo, index) => (
          <Image
            key={photo.src}
            src={photo.src}
            width={photo.width}
            height={photo.height}
            alt={photo.alt}
            className="my-4 hover:opacity-70 cursor-pointer"
            onClick={() => {
              lightboxRef.current?.openGallery(index);
            }}
          />
        ))}
      </Masonry>
      <LightGalleryComponent
        onInit={(ref) => {
          if (ref) {
            lightboxRef.current = ref.instance;
          }
        }}
        speed={500}
        plugins={[lgThumbnail, lgZoom]}
        dynamic
        dynamicEl={photos.map((photo) => ({
          src: photo.src,
          thumb: photo.src,
        }))}
      />
    </>
  );
}
