import Head from 'next/head';
import Link from 'next/link';
import { Tab } from '@headlessui/react';
import Masonry from 'react-masonry-css';
import classNames from 'classnames';
import Image from 'next/image';

import 'lightgallery/css/lightgallery.css';
import 'lightgallery/css/lg-zoom.css';
import 'lightgallery/css/lg-thumbnail.css';

import lgThumbnail from 'lightgallery/plugins/thumbnail';
import lgZoom from 'lightgallery/plugins/zoom';

import bgImage from '../public/images/photography-bg.jpg';

import ocean1 from '../public/images/ocean-1.jpeg';
import ocean2 from '../public/images/ocean-2.jpeg';
import ocean3 from '../public/images/ocean-3.jpeg';
import ocean4 from '../public/images/ocean-4.jpeg';
import ocean5 from '../public/images/ocean-5.jpeg';
import { useRef } from 'react';
import LightGalleryComponent from 'lightgallery/react';
import type { LightGallery } from 'lightgallery/lightgallery';

const tabs = [
  {
    name: 'All',
  },
  {
    name: 'Ocean',
  },
  {
    name: 'Forest',
  },
];

const images = [
  {
    src: '/images/ocean-1.jpeg',
    thumb: '/images/ocean-1.jpeg',
  },
  {
    src: '/images/ocean-2.jpeg',
    thumb: '/images/ocean-1.jpeg',
  },
  {
    src: '/images/ocean-3.jpeg',
    thumb: '/images/ocean-3.jpeg',
  },
  {
    src: '/images/ocean-4.jpeg',
    thumb: '/images/ocean-4.jpeg',
  },
  {
    src: '/images/ocean-5.jpeg',
    thumb: '/images/ocean-5.jpeg',
  },
];

export default function Home() {
  const lightboxRef = useRef<LightGallery | null>(null);

  return (
    <div className="h-full overflow-auto">
      <Head>
        <title>Photography Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <Image
        className="fixed left-0 top-0"
        src={bgImage}
        alt=""
        placeholder="blur"
      />

      <div className="fixed left-0 top-0 w-full h-full from-stone-900 bg-gradient-to-t"></div>

      <header className="fixed top-0 w-full z-30 flex justify-between items-center h-[90px] px-6">
        <div className="hidden">hm</div>
        <span className="uppercase font-medium text-lg">
          Photography Portfolio
        </span>
        <Link
          href="#"
          className="rounded-3xl bg-white text-stone-600 px-5 py-3 hover:bg-opacity-90"
        >
          Get in touch
        </Link>
      </header>

      <main className="relative pt-[110px] z-20">
        <div className="flex flex-col items-center h-full">
          <Tab.Group>
            <Tab.List className="flex items-center gap-4">
              {tabs.map((tab, index) => (
                <Tab key={`${tab}-${index}`} className="p-2 uppercase">
                  {({ selected }) => (
                    <span
                      className={classNames(
                        'uppercase text-l',
                        selected ? 'text-white' : 'text-stone-600',
                      )}
                    >
                      {tab.name}
                    </span>
                  )}
                </Tab>
              ))}
            </Tab.List>
            <Tab.Panels className="h-full max-w-[900px] w-full p-2 sm:p-4 my-6">
              <Tab.Panel>
                <Masonry
                  breakpointCols={3}
                  className="flex gap-4"
                  columnClassName=""
                >
                  {images.map((image, index) => (
                    <Image
                      key={image.src}
                      src={image.src}
                      width={500}
                      height={500}
                      alt=""
                      className="my-4 hover:opacity-70 cursor-pointer"
                      onClick={() => {
                        lightboxRef.current?.openGallery(index);
                      }}
                    />
                  ))}
                </Masonry>
                <LightGalleryComponent
                  onInit={(ref) => {
                    if (ref) {
                      lightboxRef.current = ref.instance;
                    }
                  }}
                  speed={500}
                  plugins={[lgThumbnail, lgZoom]}
                  dynamic
                  dynamicEl={images.map((image) => ({
                    src: image.src,
                    thumb: image.src,
                  }))}
                />
              </Tab.Panel>
            </Tab.Panels>
          </Tab.Group>
        </div>
      </main>

      <footer className="relative h-[90px] flex justify-center items-center uppercase text-lg font-medium z-20">
        <p>Photography Portfolio</p>
      </footer>
    </div>
  );
}
